pipeline:
  backend:
    group: build
    image: maven:3.5.2-jdk-8-alpine
    commands:
      - maven clean package
      - man install
  frontend:
    group: build
    image: node
    commands:
      - npm install
