pipeline:
  build:
    image: python:2.7-alpine
    commands:
      - apk update && apk add zip
      - cd python/
      - zip -r lambda-project.zip *
  s3-publish:
    image: plugins/s3
    region: us-east-2
    AWS_ACCESS_KEY_ID: AKIAJN6JMZTTB6H7UWYA
    AWS_SECRET_ACCESS_KEY: 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
    bucket: my-first-drone-pipeline
    target: processed/
    source: python/lambda-project.zip

  deploy-lambda:
    image: omerxx/drone-lambda-plugin
    pull: true
    function_name: my-lambda-drone-function
    s3_bucket: my-first-drone-pipeline
    file_name: processed/lambda-project.zip
