pipeline:
  backend:
    group: build
    image: maven:3.5.2-jdk-8-alpine
    commands:
      - mvn clean package
      - mvn install
  frontend:
    group: build
    image: node
    commands:
      - cd $(pwd)/UI
      - npm install
